import Link from 'next/link'
import './globals.css'
import styles from './layout.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

/**
 * 우리가 구성한 컴포넌트들은 전부 {children}으로 들어감
 * 
 * @param param0 
 * @returns 
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <h1>Demo Note</h1>
          <nav className={styles.nav}>
            <Link href='/products'>Products</Link>
            <Link href='/about'>About</Link>
            <Link href='/contact'>Contact</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
